replicaCount: 1

image:
  repository: sahilt7/hello-world-node
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
